request-id:
  header:
    name: X-Trace-Id
  channels:
    web:
      prefix: "W-"
    batch:
      prefix: "B-"

spring:
  main:
    banner-mode: off
logging:
  pattern:
    console: "%-5level %logger{36} : %msg%n"
